# Generated by Django 5.1.4 on 2025-04-04 10:20

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='created_at',
        ),
        migrations.AddField(
            model_name='code',
            name='expiration_date',
            field=models.DateTimeField(default=users.models.time_default),
        ),
    ]
