# Generated by Django 5.1.4 on 2025-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_code_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_moderator',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
