# Generated by Django 5.1.4 on 2025-04-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customusermodel_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
