# Generated by Django 5.1.7 on 2025-03-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_created_at_alter_products_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
